name       : vimix-cursors
version    : '20200224'
release    : 2
source     :
    - https://github.com/vinceliuice/Vimix-cursors/archive/2020-02-24.tar.gz : 69298d02264b5b15239c340f8fa899f91574c0eac49ad5745e8e588315423618
license    : GPL-3.0-only
component  : desktop.theme
summary    : This is an x-cursor theme inspired by Materia design and based on capitaine-cursors.
description: |
    This is an x-cursor theme inspired by Materia design and based on capitaine-cursors.
install    : |
    install -dm00755 $installdir/usr/share/icons
    cp -r dist $installdir/usr/share/icons/Vimix-cursors
    cp -r dist-white $installdir/usr/share/icons/Vimix-white-cursors
